require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RecordatoriosController do

  # This should return the minimal set of attributes required to create a valid
  # Recordatorio. As you add validations to Recordatorio, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecordatoriosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all recordatorios as @recordatorios" do
      recordatorio = Recordatorio.create! valid_attributes
      get :index, {}, valid_session
      assigns(:recordatorios).should eq([recordatorio])
    end
  end

  describe "GET show" do
    it "assigns the requested recordatorio as @recordatorio" do
      recordatorio = Recordatorio.create! valid_attributes
      get :show, {:id => recordatorio.to_param}, valid_session
      assigns(:recordatorio).should eq(recordatorio)
    end
  end

  describe "GET new" do
    it "assigns a new recordatorio as @recordatorio" do
      get :new, {}, valid_session
      assigns(:recordatorio).should be_a_new(Recordatorio)
    end
  end

  describe "GET edit" do
    it "assigns the requested recordatorio as @recordatorio" do
      recordatorio = Recordatorio.create! valid_attributes
      get :edit, {:id => recordatorio.to_param}, valid_session
      assigns(:recordatorio).should eq(recordatorio)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Recordatorio" do
        expect {
          post :create, {:recordatorio => valid_attributes}, valid_session
        }.to change(Recordatorio, :count).by(1)
      end

      it "assigns a newly created recordatorio as @recordatorio" do
        post :create, {:recordatorio => valid_attributes}, valid_session
        assigns(:recordatorio).should be_a(Recordatorio)
        assigns(:recordatorio).should be_persisted
      end

      it "redirects to the created recordatorio" do
        post :create, {:recordatorio => valid_attributes}, valid_session
        response.should redirect_to(Recordatorio.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved recordatorio as @recordatorio" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recordatorio.any_instance.stub(:save).and_return(false)
        post :create, {:recordatorio => { "user_id" => "invalid value" }}, valid_session
        assigns(:recordatorio).should be_a_new(Recordatorio)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Recordatorio.any_instance.stub(:save).and_return(false)
        post :create, {:recordatorio => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested recordatorio" do
        recordatorio = Recordatorio.create! valid_attributes
        # Assuming there are no other recordatorios in the database, this
        # specifies that the Recordatorio created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Recordatorio.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => recordatorio.to_param, :recordatorio => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested recordatorio as @recordatorio" do
        recordatorio = Recordatorio.create! valid_attributes
        put :update, {:id => recordatorio.to_param, :recordatorio => valid_attributes}, valid_session
        assigns(:recordatorio).should eq(recordatorio)
      end

      it "redirects to the recordatorio" do
        recordatorio = Recordatorio.create! valid_attributes
        put :update, {:id => recordatorio.to_param, :recordatorio => valid_attributes}, valid_session
        response.should redirect_to(recordatorio)
      end
    end

    describe "with invalid params" do
      it "assigns the recordatorio as @recordatorio" do
        recordatorio = Recordatorio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recordatorio.any_instance.stub(:save).and_return(false)
        put :update, {:id => recordatorio.to_param, :recordatorio => { "user_id" => "invalid value" }}, valid_session
        assigns(:recordatorio).should eq(recordatorio)
      end

      it "re-renders the 'edit' template" do
        recordatorio = Recordatorio.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Recordatorio.any_instance.stub(:save).and_return(false)
        put :update, {:id => recordatorio.to_param, :recordatorio => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested recordatorio" do
      recordatorio = Recordatorio.create! valid_attributes
      expect {
        delete :destroy, {:id => recordatorio.to_param}, valid_session
      }.to change(Recordatorio, :count).by(-1)
    end

    it "redirects to the recordatorios list" do
      recordatorio = Recordatorio.create! valid_attributes
      delete :destroy, {:id => recordatorio.to_param}, valid_session
      response.should redirect_to(recordatorios_url)
    end
  end

end
